### ISSUE TITLE
Downloading prerequisite datasets for recountmethylation_data_analyses.Rmd

### ISSUE THREAD

**Issue by theandyb** [metamaden/recountmethylation#21]
I'm attempting to go work through the example analyses, and the documentation refers to the user guide for instructions on how to obtain these. From my understanding, I should run the function `getdb_h5se_gm(namematch = "remethdb-h5se_gm_0-0-1_1590090412")` to get the first dataset, but when I run this it downloads the remethdb_h5se-gm_hm450k_0-0-2_1607018051 directory instead of the requested remethdb-h5se_gm_0-0-1_1590090412. Is this correct behavior for this function, or am I using the function incorrectly? (if the latter, it would be helpful for the correct code to be added to recountmethylation_data_analyses.Rmd)

**Comment by theandyb** [comment]
My understanding now is that remethdb_h5se-gm_hm450k_0-0-2_1607018051 is the newest version of the database, and that the function grabs the latest version by default; it seems to ignore the `namematch` parameter (quick look at the function seems to indicate that it isn't used when actually downloading the database?)

**Comment by theandyb** [comment]
I might have misunderstood the purpose of the `namematch` parameter

**Comment by metamaden** [comment]
Apologies for my delay in writing. I think the documentation for the namematch parameter could be improved, so I have made a note to update that documentation. Thanks for raising this issue.
